DirectoryPath: "dist"
IgnoreDirectoryMissingTrailingSlash: true
IgnoreInternalEmptyHash: true
IgnoreEmptyHref: true
IgnoreAltMissing: true
IgnoreAltEmpty: true
IgnoreURLs:
- "https://twitter.com/.*"
- "https://www.linkedin.com/company/10975051"
- "https://github.com/CortexIntelligentAutomation/docs/edit/.*"
- "https://github.com/CortexIntelligentAutomation/docs/new/.*"
- "https://github.com/CortexIntelligentAutomation/docs/issues/.*"
- ".*/_print/.*"