DirectoryPath: "dist"
IgnoreDirectoryMissingTrailingSlash: true
IgnoreInternalEmptyHash: true
IgnoreEmptyHref: true
IgnoreAltMissing: true
IgnoreAltEmpty: true
IgnoreURLs:
- "https://twitter.com/.*"
- "https://twitter.com/.*"
- "https://twitter.com/.*"
- "https://www.linkedin.com/company/10975051"
- "(https|http)://www.microsoft.com/.*"
- "https://azure.microsoft.com/.*"
- "https://css/swagger-ui.css"
- "https://js/swagger-ui-bundle.js"
- "https://js/swagger-ui-standalone-preset.js"
- "https://kodify.net/.*"
- "https://grafana.com/.*"
- "https://learn.microsoft.com/.*"
- "https://fonts.googleapis.com.*"
- "https://fonts.gstatic.com.*"
- "http://www.mimekit.net/docs/.*"
- "https://nssm.cc/"
- "https://code.visualstudio.com/"
- "https://blogs.oracle.com/.*"
- "https://jsonformatter.org/.*"
- "https://www.newtonsoft.com/.*"
- "https://.*.gov.uk/.*"
- "https://www.elastic.co/.*"
- "https://www.connectionstrings.com/.*"
- "https://dotnet.microsoft.com/.*"
IgnoreDirs:
- "docs/?.*/_print/"
- "docs/?.*/_shared/"
- "docs/2022.9/?.*/"
- "docs/2023.3/?.*/"
- "docs/2023.5/?.*/"
- "docs/2023.7/?.*/"
- "docs/2023.9/?.*/"
- "docs/2023.11/?.*/"
- "docs/2024.1/?.*/"
- "docs/2024.3/?.*/"
- "docs/2024.5/?.*/"
- "docs/2024.7/?.*/"
- "docs/2024.11/?.*/"
