DirectoryPath: "dist"
IgnoreDirectoryMissingTrailingSlash: true
IgnoreInternalEmptyHash: true
IgnoreEmptyHref: true
IgnoreAltMissing: true
IgnoreAltEmpty: true
IgnoreURLs:
- "https://twitter.com/.*"
- "https://twitter.com/.*"
- "https://twitter.com/.*"
- "https://www.linkedin.com/company/10975051"
- "(https|http)://www.microsoft.com/.*"
- "https://azure.microsoft.com/.*"
- "https://css/swagger-ui.css"
- "https://js/swagger-ui-bundle.js"
- "https://js/swagger-ui-standalone-preset.js"
- "https://kodify.net/.*"
- "https://grafana.com/.*"
- "https://learn.microsoft.com/.*"
- "https://fonts.googleapis.com.*"
- "https://fonts.gstatic.com.*"
- "http://www.mimekit.net/docs/.*"
- "https://nssm.cc/"
IgnoreDirs:
- "docs/?.*/_print/"
- "docs/?.*/_shared/"
- "docs/2022.9/?.*/"
- "docs/2023.3/?.*/"
- "docs/2023.5/?.*/"
- "docs/2023.7/?.*/"
