name: Run HTML Tests
on: pull_request
jobs:
  htmltest:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.110.0
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass Embedded
        run: sudo snap install dart-sass-embedded
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update Latest URL content
        shell: pwsh
        run: |
          .\createLatest.ps1        
      - name: npm install
        working-directory: ./
        run: |
          npm install
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: hugo --environment GitHubPages -d $GITHUB_WORKSPACE/dist
      # - name: Test HTML
      #   uses: wjdp/htmltest-action@master
      #   with:
      #     # For consistency, use the same config file as for local builds
      #     config: .htmltest.yml
      # - name: Archive htmltest results
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   # Note: Set ACTIONS_RUNTIME_TOKEN env variable to test with nektos/act
      #   with:
      #     name: htmltest-report
      #     path: tmp/.htmltest/htmltest.log
      #     retention-days: 7 # Default is 90 days
